//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HamAdept.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Czech {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Czech() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HamAdept.Localization.Czech", typeof(Czech).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O programu.
        /// </summary>
        internal static string MSG_AboutCaption {
            get {
                return ResourceManager.GetString("MSG_AboutCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HAM Adept by Sportcanon.
        /// </summary>
        internal static string MSG_AboutText {
            get {
                return ResourceManager.GetString("MSG_AboutText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zvolen výběr z problematických otázek. Nelze klást sekvenčně, přepínám na náhodný výběr..
        /// </summary>
        internal static string MSG_BackToRandom {
            get {
                return ResourceManager.GetString("MSG_BackToRandom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Importováno [@1] otázkových okruhů..
        /// </summary>
        internal static string MSG_CategoriesImported {
            get {
                return ResourceManager.GetString("MSG_CategoriesImported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Úspěšně načteno [@1] otázkových okruhů..
        /// </summary>
        internal static string MSG_CategoriesLoaded {
            get {
                return ResourceManager.GetString("MSG_CategoriesLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Správně.
        /// </summary>
        internal static string MSG_Correct {
            get {
                return ResourceManager.GetString("MSG_Correct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Všechna data uložená data statistik budou vymazána! \r\nOpravdu vymazat všechny statistiky?.
        /// </summary>
        internal static string MSG_DeletingStatistics {
            get {
                return ResourceManager.GetString("MSG_DeletingStatistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seznam problematických otázek byl vyčerpán..
        /// </summary>
        internal static string MSG_ProblematicEmpty {
            get {
                return ResourceManager.GetString("MSG_ProblematicEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Importováno [@1] testových otázek..
        /// </summary>
        internal static string MSG_QuestionsImported {
            get {
                return ResourceManager.GetString("MSG_QuestionsImported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Úspěšně načteno [@1] testových otázek..
        /// </summary>
        internal static string MSG_QuestionsLoaded {
            get {
                return ResourceManager.GetString("MSG_QuestionsLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Otázka vybrána náhodně z chybně zodpovězených..
        /// </summary>
        internal static string MSG_SelectedFromProblematic {
            get {
                return ResourceManager.GetString("MSG_SelectedFromProblematic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zvolena otázka [@1].
        /// </summary>
        internal static string MSG_SelectedQuestion {
            get {
                return ResourceManager.GetString("MSG_SelectedQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statistická data byla vymazána!.
        /// </summary>
        internal static string MSG_StatisticsDeletingDone {
            get {
                return ResourceManager.GetString("MSG_StatisticsDeletingDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Přepínám na výběr ze všech otázek..
        /// </summary>
        internal static string MSG_SwitchingToAll {
            get {
                return ResourceManager.GetString("MSG_SwitchingToAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Varování.
        /// </summary>
        internal static string MSG_Warning {
            get {
                return ResourceManager.GetString("MSG_Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vítej budoucí HAM operátore!.
        /// </summary>
        internal static string MSG_Welcome {
            get {
                return ResourceManager.GetString("MSG_Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Špatně.
        /// </summary>
        internal static string MSG_Wrong {
            get {
                return ResourceManager.GetString("MSG_Wrong", resourceCulture);
            }
        }
    }
}
